<!DOCTYPE html>
<html lang="pt">
<head>
  <meta charset="UTF-8">
  <title>Lista de Alunos</title>
</head>
<body>
  
  <table>
    <tr>
      <th>Matrícula</th>
      <th>Nome</th>
      <th>Curso</th>
    </tr>
    <?php foreach ($alunos as $aluno): ?>
    <tr>
      <td><?= $aluno->matricula ?></td>
      <td><?= $aluno->nome ?></td>
      <td><?= $aluno->curso ?></td>
    </tr>
    <?php endforeach ?>
  </table>

</body>
</html>